replicaCount: 1

image:
  repository: obsidiandynamics/kafdrop
  tag: latest
  pullPolicy: Always

kafka:
  brokerConnect: localhost:9092
  properties: ""
  truststore: ""
  keystore: ""
  propertiesFile: "kafka.properties"
  truststoreFile: "kafka.truststore.jks"
  keystoreFile: "kafka.keystore.jks"

host:

jvm:
  opts: ""
jmx:
  port: 8686

nameOverride: ""
fullnameOverride: ""

cmdArgs: ""

server:
  port: 9000
  servlet:
    contextPath: /

service:
  annotations: {}
  type: NodePort
  port: 9000
  nodePort: 30900

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts: []
  tls: []

resources:
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
    cpu: 1m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

mountProtoDesc:
  enabled: true
  descFiles:
    proto.desc: |-
      
      +lib/kafka_proto/keypay/keypay.webhook.protoKafkaProto.Keypay.Webhook"â
      NotificationData
      id (Rid'
      updated_section (	RupdatedSection3
      pay_condition_rule_set (	RpayConditionRuleSet%
      leave_template (	RleaveTemplate9
      super_fund1_member_number (	RsuperFund1MemberNumber"e
      Notification
      event (	Revent?
      data (2+.KafkaProto.Keypay.Webhook.NotificationDataRdatabproto3
